export const specialKeyStyles: Record<string, string> = {
  ShiftLeft: "flex-1 h-10",
  ShiftRight: "flex-1 h-10",
  ControlLeft: "flex-1 h-10",
  ControlRight: "flex-1 h-10",
  AltLeft: "flex-1 h-10",
  AltRight: "flex-1 h-10",
  Space: "w-[270px] h-10",
  Enter: "flex-[1_1_auto] h-10",
  CapsLock: "flex-1 h-10",
  Tab: "flex-1 h-10",
  Backslash: "flex-1 h-10",
  Backspace: "flex-1 h-10",
  ...Object.fromEntries(Array.from({ length: 12 }, (_, i) => [`F${i + 1}`, "h-6 flex-1"])),
  Escape: "h-6 flex-1",
  ArrowUp: "h-5 w-10 rounded-t",
  ArrowLeft: "h-5 w-10 rounded",
  ArrowDown: "h-5 w-10 rounded-b",
  ArrowRight: "h-5 w-10 rounded",
  MetaLeft: "flex-1 h-10",
};
