export const specialKeyStyles: Record<string, string> = {
  ShiftLeft: "flex-1 h-8",
  ShiftRight: "flex-1 h-8",
  ControlLeft: "flex-1 h-8",
  ControlRight: "flex-1 h-8",
  AltLeft: "flex-1 h-8",
  AltRight: "flex-1 h-8",
  Space: "w-[270px] h-8",
  Enter: "flex-[1_1_auto] h-8",
  CapsLock: "flex-1 h-8",
  Tab: "flex-1 h-8",
  Backslash: "flex-1 h-8",
  Backspace: "flex-1 h-8",
  ...Object.fromEntries(Array.from({ length: 12 }, (_, i) => [`F${i + 1}`, "h-6 flex-1"])),
  Escape: "h-6 flex-1",
  ArrowUp: "h-4 w-8 rounded-t",
  ArrowLeft: "h-4 w-8 rounded",
  ArrowDown: "h-4 w-8 rounded-b",
  ArrowRight: "h-4 w-8 rounded",
  MetaLeft: "flex-1 h-8",
};
